monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-santos10-audio-machine"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = true
        api.alsa.use-ucm = true
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_output.platform-santos10-audio-machine.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
        audio.rate = 48000
        audio.channels = 2
        audio.position = [ FL, FR ]
        api.alsa.period-size = 1024
        api.alsa.headroom = 1024
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_input.platform-santos10-audio-machine.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
        audio.rate = 48000
        audio.channels = 2
        audio.position = [ FL, FR ]
        api.alsa.period-size = 1024
        api.alsa.headroom = 1024
      }
    }
  }
]
